# $$ Pandas -  Assignment $$ 


## $ Author : Akula Venkata Satya  Sai Gopinadh $

### $ Important Points $

##### 1.For Version Checking -------   'pd.version'
##### 2.For Seeing Versions -------    'pd.show_versions(as_json=True)'
##### 3.Creating Series -------     'pd.Series(##)'
##### 4.Converting Index of a Series into a Column in the Data Frame --------     'dataframe = series.to_frame().reset_index()'
##### 5.Combining Many Series to form a Dataframe --------     'df = pd.concat([series1, series2], axis=1)'

##### np.random.randint(1, 10, 35)
##### series_union = pd.Series(np.union1d(series1, series2))  # union
##### series_intersection = pd.Series(np.intersect1d(series1, series2))  # intersect
##### series_union[~series_union.isin(series_intersection)]
##### ser.value_counts()
##### ser.values.reshape(7,5)

In [1]:
import numpy as np


### 1. How to import pandas and check the version?

In [2]:
import pandas as pd 

pd.__version__

'1.4.3'

In [3]:
pd.show_versions(as_json=True)

{
  "system": {
    "commit": "e8093ba372f9adfe79439d90fe74b0b5b6dea9d6",
    "python": "3.9.13.final.0",
    "python-bits": 64,
    "OS": "Windows",
    "OS-release": "10",
    "Version": "10.0.19044",
    "machine": "AMD64",
    "processor": "Intel64 Family 6 Model 23 Stepping 10, GenuineIntel",
    "byteorder": "little",
    "LC_ALL": null,
    "LANG": null,
    "LOCALE": {
      "language-code": "English_United States",
      "encoding": "1252"
    }
  },
  "dependencies": {
    "pandas": "1.4.3",
    "numpy": "1.23.1",
    "pytz": "2022.1",
    "dateutil": "2.8.2",
    "setuptools": "58.1.0",
    "pip": "22.3",
    "Cython": null,
    "pytest": null,
    "hypothesis": null,
    "sphinx": null,
    "blosc": null,
    "feather": null,
    "xlsxwriter": null,
    "lxml.etree": null,
    "html5lib": null,
    "pymysql": null,
    "psycopg2": null,
    "jinja2": "3.1.2",
    "IPython": "8.4.0",
    "pandas_datareader": null,
    "bs4": "4.11.1",
    "bottleneck": null,
    "brotli": nu

### 2. How to create a series from a list, numpy array and dict?

In [4]:
# List

list1 = list('SatyaSai')

# Array

array = np.arange(8)

# Dictionary

dict1 = dict(zip(list1, array))


# Creating Series from the above list,array and dict

series1 = pd.Series(list1)


series2 = pd.Series(array)


series3 = pd.Series(dict1)

print(series3.head(10))

print(series3.info())


S    5
a    6
t    2
y    3
i    7
dtype: int32
<class 'pandas.core.series.Series'>
Index: 5 entries, S to i
Series name: None
Non-Null Count  Dtype
--------------  -----
5 non-null      int32
dtypes: int32(1)
memory usage: 60.0+ bytes
None


 ### 3. How to convert the index of a series into a column of a dataframe?

In [5]:
# List

list1 = list('SatyaSai')

# Array

array = np.arange(8)

# Dictionary

dict1 = dict(zip(list1, array))


series  = pd.Series(dict1)

dataframe = series.to_frame().reset_index()

print(dataframe.head())

  index  0
0     S  5
1     a  6
2     t  2
3     y  3
4     i  7


### 4. How to combine many series to form a dataframe?

In [6]:
series1 = pd.Series(list('venkatasatya'))

series2 = pd.Series(np.arange(9))

df = pd.concat([series1, series2], axis=1)

print(df.head())

   0    1
0  v  0.0
1  e  1.0
2  n  2.0
3  k  3.0
4  a  4.0


### 5. How to assign name to the series’ index?

In [7]:
ser1 = pd.Series(list('Venkatsgn'))

ser1.name = 'Myname'

ser1.head(10)

0    V
1    e
2    n
3    k
4    a
5    t
6    s
7    g
8    n
Name: Myname, dtype: object

### 6. How to get the items of series A not present in series B?

In [8]:
ser1 = pd.Series([1,2,3,4,8,9])

ser2 = pd.Series([1,7,10,45,2,9])

for i in range(len(ser1)):
    for j in range(len(ser2)):
        if ser1[i] == ser2[j]:
            continue
    else: 
        print(ser1[i])
    

1
2
3
4
8
9


### 7. How to get the items not common to both series A and series B?

In [9]:
"""ser1 = pd.Series([1,2,3,4,8,9])

ser2 = pd.Series([1,7,10,45,2,9])

for i in range(len(ser1)):
    for j in range(len(ser2)):
        if ser1[i] == ser2[i]:
            continue
            print[i]
    else: 
        break
"""
series1 = pd.Series([1,2,3,4,8,9])

series2 = pd.Series([1,7,10,45,2,9])

series_union = pd.Series(np.union1d(series1, series2))  # union
series_intersection = pd.Series(np.intersect1d(series1, series2))  # intersect
series_union[~series_union.isin(series_intersection)]

2     3
3     4
4     7
5     8
7    10
8    45
dtype: int64

### 8. How to get frequency counts of unique items of a series?

In [10]:
ser = pd.Series(np.take(list('Satya'), np.random.randint(5, size=50)))

ser.value_counts()

a    22
y    11
S     9
t     8
dtype: int64

### 9. How to convert a numpy array to a dataframe of given shape?

In [11]:
ser = pd.Series(np.random.randint(1, 10, 35))

df = pd.DataFrame(ser.values.reshape(7,5))

df

0  1  2  3  4
0  1  4  4  6  5
1  4  4  6  8  7
2  7  6  5  4  6
3  8  5  6  8  6
4  5  7  7  7  3
5  3  3  9  9  4
6  3  2  7  6  4

In [12]:
array = np.array([[11, 22, 33], 
                  [35, 25, 55]])

temp = pd.DataFrame(array)


print(temp)

    0   1   2
0  11  22  33
1  35  25  55


### 10. How to extract items at given positions from a series?


In [13]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

ser.take(pos)

0     a
4     e
8     i
14    o
20    u
dtype: object

### 11. How to stack two series vertically and horizontally ?

In [14]:
a = pd.Series(['S','a','t','y','a','S','a','i'])
b = pd.Series([1,2,3,4,5,6,7,8])

print('vertical Stack')
print(pd.concat([a,b],axis = 0))


print('Horizontal stack')
print(pd.concat([a,b],axis = 1))


vertical Stack
0    S
1    a
2    t
3    y
4    a
5    S
6    a
7    i
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: object
Horizontal stack
   0  1
0  S  1
1  a  2
2  t  3
3  y  4
4  a  5
5  S  6
6  a  7
7  i  8


### 12. How to compute difference of differences between consequtive numbers of a series?

In [15]:

ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])


print(ser.diff().tolist())
print(ser.diff().diff().tolist())

[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]
[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]


### 13.How to import only specified columns from a csv file?

In [18]:
df = pd.read_csv('./births.csv')

df.loc[:,["Gender","Number"]]

print(df.head(10))

   Year  District Code District Name  Neighborhood Code  \
0  2017              1  Ciutat Vella                  1   
1  2017              1  Ciutat Vella                  2   
2  2017              1  Ciutat Vella                  3   
3  2017              1  Ciutat Vella                  4   
4  2017              2      Eixample                  5   
5  2017              2      Eixample                  6   
6  2017              2      Eixample                  7   
7  2017              2      Eixample                  8   
8  2017              2      Eixample                  9   
9  2017              2      Eixample                 10   

                       Neighborhood Name Gender  Number  
0                               el Raval   Boys     283  
1                         el Barri Gòtic   Boys      56  
2                         la Barceloneta   Boys      51  
3  Sant Pere, Santa Caterina i la Ribera   Boys      90  
4                          el Fort Pienc   Boys     117  
5 

### 14. How to keep only top 2 most frequent values as it is and replace everything else as ‘Other’?

In [19]:
series = pd.Series([1,2,3,1,1,4,2,9,8,2,6,5,1,4,8,7,1])
  
freq = series.value_counts()
  
series[~series.isin(freq .index[:2])] = 'other'
print(series)

0         1
1         2
2     other
3         1
4         1
5     other
6         2
7     other
8     other
9         2
10    other
11    other
12        1
13    other
14    other
15    other
16        1
dtype: object


### 15. How to get the minimum, 25th percentile, median, 75th, and max of a numeric series?

In [20]:
state = np.random.RandomState(800)
a = pd.Series(state.normal(10, 5, 25))


np.percentile(a, q=[0, 25, 50, 75, 100])

array([-6.4594609 ,  6.2463693 ,  8.57890491, 11.02034932, 14.65168241])

### 16. How to get frequency counts of unique items of a series?

In [21]:
a = pd.Series([1,2,3,1,5,4,2,9,8,7,6,5])
 
print(a)
print(a.value_counts())

0     1
1     2
2     3
3     1
4     5
5     4
6     2
7     9
8     8
9     7
10    6
11    5
dtype: int64
1    2
2    2
5    2
3    1
4    1
9    1
8    1
7    1
6    1
dtype: int64


### 17. How to get the positions of items of series A in another series B?

In [22]:
a = pd.Series([1,2,3,1,5,4,2,9,8,7,6,5])
b = pd.Series([1,3,5,7,9])

print("Positions of items of b in a:")
[pd.Index(a).get_loc(i) for i in b]

Positions of items of b in a:


[array([ True, False, False,  True, False, False, False, False, False,
        False, False, False]),
 2,
 array([False, False, False, False,  True, False, False, False, False,
        False, False,  True]),
 9,
 7]

### 18. How to compute the mean squared error on a truth and predicted series?

In [23]:
truth = pd.Series(range(10))
pred = pd.Series(range(10) + np.random.random(10))

np.mean((truth-pred)**2)

0.15305963988889443

### 19. How to calculate the number of characters in each word in a series?

In [24]:
x = pd.Series(['Satya','Pandas','Matplotlib'])

x.map(lambda x: len(x))

0     5
1     6
2    10
dtype: int64

### 20. How to convert the first character of each element in a series to uppercase?

In [25]:
a = pd.Series(['Satya','Wishes','you','Happy','Diwali'])

a.map(lambda x: x.title())
a.map(lambda x: x[0].upper() + x[1:])
pd.Series([i.title() for i in a])

0     Satya
1    Wishes
2       You
3     Happy
4    Diwali
dtype: object

### 21. How to compute the euclidean distance between two series?

In [26]:
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([11,12,13,14,15,16,17,18,19,20])

sum((p - q)**2)**.5

31.622776601683793

### 22. How to import only every nth row from a csv file to create a dataframe?

In [27]:
df = pd.read_csv('accidents_2017.csv', chunksize=50)
df2 = pd.concat([chunk.iloc[0] for chunk in df], axis=1)
df2 = df2.transpose()
df2

Id   District Name  \
0      2017S008429             Unknown   
50     2017S000869          Sant Martí   
100    2017S005878          Sant Martí   
150    2017S006098          Sant Martí   
200    2017S004227        Ciutat Vella   
...                ...             ...   
10100  2017S002122              Gràcia   
10150  2017S000028      Horta-Guinardó   
10200  2017S000167          Nou Barris   
10250  2017S007678          Nou Barris   
10300  2017S005306         Sant Andreu   

                                  Neighborhood Name  \
0                                           Unknown   
50                       el Camp de l'Arpa del Clot   
100                         Provençals del Poblenou   
150    Diagonal Mar i el Front Marítim del Poblenou   
200           Sant Pere, Santa Caterina i la Ribera   
...                                             ...   
10100            el Camp d'en Grassot i Gràcia Nova   
10150                          la Font d'en Fargues   
10200                                    Torre Baró   
10250                           el Turó de la Peira   
10300                                   Sant Andreu   

                                                  Street    Weekday  \
0      Número 27                                     ...     Friday   
50     AV MERIDIANA                                  ...  Wednesday   
100    Corts Catalanes / Selva de Mar                ...  Wednesday   
150    Llevant / Diagonal                            ...   Thursday   
200    Ciutadella                                    ...     Friday   
...                                                  ...        ...   
10100  PI I MARGALL / Hipòlit Lázaro                 ...   Thursday   
10150  MAURICI VILOMARA / Montse Casanovas           ...     Monday   
10200  AV M DÉU MONTSERRA                            ...     Sunday   
10250  Cadí / Peira                                  ...   Saturday   
10300  Gran de Sant Andreu                           ...   Saturday   

           Month Day Hour Part of the day Mild injuries Serious injuries  \
0        October  13    8         Morning             2                0   
50      February   1   18       Afternoon             1                0   
100         July   5   16       Afternoon             0                0   
150         July  13   12         Morning             1                0   
200          May  12   14       Afternoon             0                0   
...          ...  ..  ...             ...           ...              ...   
10100      March  16   17       Afternoon             1                0   
10150    January   2   10         Morning             2                0   
10200    January   8    5           Night             0                0   
10250  September  16   20       Afternoon             1                0   
10300       June  17    9         Morning             1                0   

      Victims Vehicles involved Longitude   Latitude  
0           2                 2  2.125624  41.340045  
50          1                 2  2.186557  41.409004  
100         0                 2  2.201634  41.414447  
150         1                 2  2.219305  41.411328  
200         0                 1  2.186597  41.388181  
...       ...               ...       ...        ...  
10100       1                 2   2.16352  41.407416  
10150       2                 1  2.162445  41.423321  
10200       0                 7   2.17468  41.422158  
10250       1                 2  2.169326  41.431997  
10300       1                 1  2.188972   41.43843  

[207 rows x 15 columns]

### 23. How to change column values when importing csv to a dataframe?

In [28]:
df = pd.read_csv('births.csv',converters={'region_code': lambda x: 'South' if float(x) > 50 else 'North'})
df

Year  District Code District Name  Neighborhood Code  \
0    2017              1  Ciutat Vella                  1   
1    2017              1  Ciutat Vella                  2   
2    2017              1  Ciutat Vella                  3   
3    2017              1  Ciutat Vella                  4   
4    2017              2      Eixample                  5   
..    ...            ...           ...                ...   
729  2013             10    Sant Martí                 70   
730  2013             10    Sant Martí                 71   
731  2013             10    Sant Martí                 72   
732  2013             10    Sant Martí                 73   
733  2013             99     No consta                 99   

                         Neighborhood Name Gender  Number  
0                                 el Raval   Boys     283  
1                           el Barri Gòtic   Boys      56  
2                           la Barceloneta   Boys      51  
3    Sant Pere, Santa Caterina i la Ribera   Boys      90  
4                            el Fort Pienc   Boys     117  
..                                     ...    ...     ...  
729                  el Besòs i el Maresme  Girls      93  
730                Provençals del Poblenou  Girls      95  
731               Sant Martí de Provençals  Girls      97  
732                    la Verneda i la Pau  Girls      94  
733                              No consta  Girls       2  

[734 rows x 7 columns]

### 24. How to import only specified columns from a csv file?

In [29]:
df = pd.read_csv('births.csv', usecols=['Gender', 'Number'])
print(df.head())

  Gender  Number
0   Boys     283
1   Boys      56
2   Boys      51
3   Boys      90
4   Boys     117


### 25. How to rename a specific columns in a dataframe?

In [30]:
df = pd.read_csv('births.csv')
print("Before Renaming!...")
print(df.columns)
df=df.rename(columns = {'Number':'Count'})
print("After Renaming!...")
print(df.columns)

Before Renaming!...
Index(['Year', 'District Code', 'District Name', 'Neighborhood Code',
       'Neighborhood Name', 'Gender', 'Number'],
      dtype='object')
After Renaming!...
Index(['Year', 'District Code', 'District Name', 'Neighborhood Code',
       'Neighborhood Name', 'Gender', 'Count'],
      dtype='object')


### 26. How to check if a dataframe has any missing values?

In [31]:
df = pd.read_csv('births.csv')
df.isnull().values.any()

False

### 27. How to count the number of missing values in each column?

In [32]:
df = pd.read_csv('deaths.csv')
missing_col = df.apply(lambda x: x.isnull().sum())
missing_col.argmax()

0

### 28. How to swap two rows of a dataframe?

In [33]:
df = pd.DataFrame(np.arange(100).reshape(10, -1))

def swap_two_rows(df, i1, i2):
    a, b = df.iloc[i1, :].copy(), df.iloc[i2, :].copy()
    df.iloc[i1, :], df.iloc[i2, :] = b, a
    return df

swap_two_rows(df, 1, 2)

0   1   2   3   4   5   6   7   8   9
0   0   1   2   3   4   5   6   7   8   9
1  20  21  22  23  24  25  26  27  28  29
2  10  11  12  13  14  15  16  17  18  19
3  30  31  32  33  34  35  36  37  38  39
4  40  41  42  43  44  45  46  47  48  49
5  50  51  52  53  54  55  56  57  58  59
6  60  61  62  63  64  65  66  67  68  69
7  70  71  72  73  74  75  76  77  78  79
8  80  81  82  83  84  85  86  87  88  89
9  90  91  92  93  94  95  96  97  98  99

### 29. How to reverse the rows of a dataframe?

In [34]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))

print(df)
print('\ndata after reversing the rows')
print(df.loc[df.index[::-1], :])

    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

data after reversing the rows
    0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4


### 30. How to remove rows from a dataframe that are present in another dataframe?

In [35]:
df1 = np.random.randint(1,5,16).reshape(4, -1)

print('data_1 : ')
print(df1)
df2 = np.random.randint(1,5,16).reshape(4, -1)

print('\ndata_2 :')
print(df2)

print(df1[~df1.isin(df2).all(1)])

data_1 : 
[[3 4 1 1]
 [3 2 4 1]
 [3 1 3 1]
 [1 2 1 2]]

data_2 :
[[4 1 4 4]
 [2 4 3 1]
 [3 2 4 1]
 [3 1 2 3]]


AttributeError: 'numpy.ndarray' object has no attribute 'isin'

### 31. How to convert a series of date-strings to a timeseries?

In [36]:
dates = pd.Series(['06 Jan 1978', '20120102', '20120303', '2013/04/04', '2014-05-15', '2015-06-06T12:20'])
from dateutil.parser import parse
dates.map(lambda x: parse(x))

0   1978-01-06 00:00:00
1   2012-01-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-15 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

### 32. How to filter words that contain atleast 2 vowels from a series?

In [39]:
from collections import Counter

a = pd.Series(['Narasaraopet', 'Guntur', 'Vijayawada', 'India','Chilakaluripet'])

mask = a.map(lambda x: sum([Counter(x.lower()).get(i, 0) for i in list('aeiou')]) >= 2)
a[mask]

0      Narasaraopet
2            Guntur
3        Vijayawada
4             India
5    Chilakaluripet
dtype: object

### 33. How to get the mean of a series grouped by another series?

In [41]:
Students_names = pd.Series(np.random.choice(['satya', 'sai', 'venkat','krishna'], 10))

marks= pd.Series(np.linspace(1, 100, 10))

print(Students_names.tolist())
print(marks.tolist())

marks.groupby(Students_names).mean()

['venkat', 'krishna', 'satya', 'venkat', 'krishna', 'venkat', 'sai', 'sai', 'venkat', 'sai']
[1.0, 12.0, 23.0, 34.0, 45.0, 56.0, 67.0, 78.0, 89.0, 100.0]


krishna    28.500000
sai        81.666667
satya      23.000000
venkat     45.000000
dtype: float64

### 34. How to compute the euclidean distance between two series?

In [42]:
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([11,12,13,14,15,16,17,18,19,20])

sum((p - q)**2)**.5


31.622776601683793

### 35. How to get the day of month, week number, day of year and day of week from a series of date strings?

In [43]:
dates = pd.Series(['01 Jan 2010', '16-11-2001', '20120303', '2013/04/04', '2015-06-06T12:20'])

from dateutil.parser import parse
temp = dates.map(lambda x: parse(x))

print("Date: ", temp.dt.day.tolist())

print("Day number of year: ", temp.dt.dayofyear.tolist())


Date:  [1, 16, 3, 4, 6]
Day number of year:  [1, 320, 63, 94, 157]


### 36. How to convert year-month string to dates corresponding to the 4th day of the month?

In [44]:
from dateutil.parser import parse

ser = pd.Series(['Jan 2020', 'Feb 2021', 'Mar 2022'])


ser_ts = ser.map(lambda x: parse(x))
ser_datestr = ser_ts.dt.year.astype('str') + '-' + ser_ts.dt.month.astype('str') + '-' + '04'

[parse(i).strftime('%Y-%m-%d') for i in ser_datestr]


['2020-01-04', '2021-02-04', '2022-03-04']

### 37. How to find all the local maxima (or peaks) in a numeric series?

In [45]:
w = pd.Series(np.random.randint(1, 5, 10))
print(w)
y = np.diff(np.sign(np.diff(w)))
peak_locs = np.where(y == -2)[0] + 1
peak_locs

0    1
1    1
2    2
3    4
4    1
5    3
6    2
7    2
8    1
9    2
dtype: int32


array([3, 5], dtype=int64)

### 38. How to replace missing spaces in a string with the least frequent character?

In [46]:
a = pd.Series(list('sdd sfs bgf gfer he sgaeir fbajwew'))

frequency = a.value_counts()
print(frequency)

least_freq = frequency.dropna().index[-1]
"".join(a.replace(' ', least_freq))

     6
s    4
f    4
e    4
g    3
d    2
b    2
r    2
a    2
w    2
h    1
i    1
j    1
dtype: int64


'sddjsfsjbgfjgferjhejsgaeirjfbajwew'

### 39. How to compute the autocorrelations of a numeric series?

In [47]:
a = pd.Series(np.arange(10) + np.random.normal(1, 5, 10))

autocorrelations = [a.autocorr(i).round(2) for i in range(9)]
print(autocorrelations[1:])
print('Lag having highest correlation: ', np.argmax(np.abs(autocorrelations[1:]))+1)

[-0.18, 0.41, 0.41, -0.04, 0.15, 0.93, -0.96, 1.0]
Lag having highest correlation:  8


### 40. How to set the number of rows and columns displayed in the output?

In [50]:
df = pd.read_csv('births.csv')

pd.set_option('display.max_columns', 5)
pd.set_option('display.max_rows', 5)

df

Year  District Code  ... Gender  Number
0    2017              1  ...   Boys     283
1    2017              1  ...   Boys      56
..    ...            ...  ...    ...     ...
732  2013             10  ...  Girls      94
733  2013             99  ...  Girls       2

[734 rows x 7 columns]

### 41. How to format all the values in a dataframe as percentages?

In [51]:
df = pd.DataFrame(np.random.random(10), columns=['random_percentages'])

out = df.style.format({'random_percentages': '{0:.5%}'.format,})

out

### 42. How to filter every nth row in a dataframe?

In [52]:
df = pd.read_csv('births.csv')
print(df.iloc[::3, :][['District Code', 'Gender', 'Number']])

     District Code Gender  Number
0                1   Boys     283
3                1   Boys      90
..             ...    ...     ...
729             10  Girls      93
732             10  Girls      94

[245 rows x 3 columns]


### 43. How to get the row number of the nth largest value in a column?

In [60]:
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))

n = 9
df['a'].argsort()[::-1][n]




7

### 44. How to get the positions where values of two columns match?

In [61]:
df1 = np.random.randint(1,5,16).reshape(4, -1)

print('data_1 : ')
print(df1)
df2 = np.random.randint(1,5,16).reshape(4, -1)

print('\ndata_2 :')
print(df2)

np.where(df1 == df2)

data_1 : 
[[2 2 2 4]
 [3 1 1 3]
 [3 4 3 4]
 [1 4 3 1]]

data_2 :
[[3 4 1 4]
 [4 1 3 1]
 [4 2 4 1]
 [4 3 2 3]]


(array([0, 1], dtype=int64), array([3, 1], dtype=int64))

### 45. How to get the frequency of unique values in the entire dataframe?

In [62]:
df = pd.DataFrame(np.random.randint(1, 10, 20).reshape(-1, 4))

print(df)

pd.value_counts(df.values.ravel())

   0  1  2  3
0  9  2  6  8
1  9  4  9  4
2  1  5  5  5
3  1  1  8  4
4  8  7  3  9


9    4
8    3
    ..
7    1
3    1
Length: 9, dtype: int64

### 46. How to replace both the diagonals of dataframe with 0?

In [63]:
df = pd.DataFrame(np.random.randint(1,5,9).reshape(3, -1))

print(df)

for i in range(df.shape[0]):
    df.iat[i, i] = 0
    df.iat[df.shape[0]-i-1, i] = 0
    
print('\nmatrix after making the diagnol elements o :' )
print(df)

   0  1  2
0  2  1  3
1  2  4  3
2  2  2  1

matrix after making the diagnol elements o :
   0  1  2
0  0  1  0
1  2  0  3
2  0  2  0
